language: c

sudo: false

notifications:
  email: false

env:
  global:
    - SETUP_XVFB=True
    - CONDA_CHANNELS="conda-forge"
    - DEBUG=True
  matrix:
    - PYTHON_VERSION=2.7

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - echo $PATH
  - which conda

script:
  - py.test glue_medical
